// <auto-generated />
namespace ManagementSystemVersionTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Calendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Calendar));
        
        string IMigrationMetadata.Id
        {
            get { return "202104031626431_Calendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
